spring:
  h2:
    console:
      enabled: true

  daatasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    job:
      enabled: false

input:
  file: classpath:user.csv